### ISSUE TITLE
Suggest changing default Run Behavior

### ISSUE THREAD

**Issue by mknabe** [wesbaker/alfred-boardgamegeek#165]
Huge fan of this workflow. I'd just like to suggest that you change the default Run Behavior to delay sending the request until the user is finished typing to avoid spamming the API. 

These are the settings I'm using. It also helps avoid the stuttering effect when multiple requests are finishing.

![Screenshot 2021-08-03 at 11 07 58](https://user-images.githubusercontent.com/5341280/128049144-577968d4-8320-4ca1-9c63-3acef5e52c46.png)

**Comment by wesbaker** [comment]
I haven’t seen any stuttering myself, but I like the idea. I’m not sure if https://github.com/sindresorhus/alfy supports it, but I’ll ask.

**Comment by wesbaker** [comment]
Whoops, I think it’s just a matter of updating the plist…let’s see if that works.

**Comment by wesbaker** [comment]
Looks like the above PR fixes it and the latest version has been published to npm. Let me know if you have any issues.

**Comment by mknabe** [comment]
Thanks!
